/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://dev-portal.onshape.com/): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.181.37085-cf05a13421a3
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTInstanceControlNode750 } from './BTInstanceControlNode750';
import {
    BTInstanceControlNode750FromJSON,
    BTInstanceControlNode750FromJSONTyped,
    BTInstanceControlNode750ToJSON,
} from './BTInstanceControlNode750';
import type { BTMAssemblyFeature887 } from './BTMAssemblyFeature887';
import {
    BTMAssemblyFeature887FromJSON,
    BTMAssemblyFeature887FromJSONTyped,
    BTMAssemblyFeature887ToJSON,
} from './BTMAssemblyFeature887';
import type { BTMAssemblyMirrorFeature3037 } from './BTMAssemblyMirrorFeature3037';
import {
    BTMAssemblyMirrorFeature3037FromJSON,
    BTMAssemblyMirrorFeature3037FromJSONTyped,
    BTMAssemblyMirrorFeature3037ToJSON,
} from './BTMAssemblyMirrorFeature3037';
import type { BTMSuppressionState1924 } from './BTMSuppressionState1924';
import {
    BTMSuppressionState1924FromJSON,
    BTMSuppressionState1924FromJSONTyped,
    BTMSuppressionState1924ToJSON,
} from './BTMSuppressionState1924';
import type { BTParametricInstance2641 } from './BTParametricInstance2641';
import {
    BTParametricInstance2641FromJSON,
    BTParametricInstance2641FromJSONTyped,
    BTParametricInstance2641ToJSON,
 BTParametricInstance2641SuperToJSON,
} from './BTParametricInstance2641';
import type { BTReferenceCustomData1551 } from './BTReferenceCustomData1551';
import {
    BTReferenceCustomData1551FromJSON,
    BTReferenceCustomData1551FromJSONTyped,
    BTReferenceCustomData1551ToJSON,
} from './BTReferenceCustomData1551';
import type { BTRevisionCustomData2090 } from './BTRevisionCustomData2090';
import {
    BTRevisionCustomData2090FromJSON,
    BTRevisionCustomData2090FromJSONTyped,
    BTRevisionCustomData2090ToJSON,
} from './BTRevisionCustomData2090';

/**
 * 
 * @export
 * @interface BTAssemblyMirror2996
 */
export interface BTAssemblyMirror2996 extends BTParametricInstance2641 {
    /**
     * Type of JSON object.
     * @type {string}
     * @memberof BTAssemblyMirror2996
     */
    btType?: string;
    /**
     * 
     * @type {BTMAssemblyMirrorFeature3037}
     * @memberof BTAssemblyMirror2996
     */
    mirrorFeature?: BTMAssemblyMirrorFeature3037;
}

/**
 * Check if a given object implements the BTAssemblyMirror2996 interface.
 */
export function instanceOfBTAssemblyMirror2996(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTAssemblyMirror2996FromJSON(json: any): BTAssemblyMirror2996 {
    return BTAssemblyMirror2996FromJSONTyped(json, false);
}

export function BTAssemblyMirror2996FromJSONTyped(json: any, ignoreDiscriminator: boolean): BTAssemblyMirror2996 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...BTParametricInstance2641FromJSONTyped(json, ignoreDiscriminator),
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'mirrorFeature': !exists(json, 'mirrorFeature') ? undefined : BTMAssemblyMirrorFeature3037FromJSON(json['mirrorFeature']),
    };
}

export function BTAssemblyMirror2996ToJSON(value?: BTAssemblyMirror2996 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...BTParametricInstance2641SuperToJSON(value),
        'btType': value.btType,
        'mirrorFeature': BTMAssemblyMirrorFeature3037ToJSON(value.mirrorFeature),
    };
}

