/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.196.54436-927372740f35
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTVector3d389 } from './BTVector3d389';
import {
    BTVector3d389FromJSON,
    BTVector3d389FromJSONTyped,
    BTVector3d389ToJSON,
} from './BTVector3d389';

import {
     BTNonAlignedBoundingBox4180FromJSONTyped,
    BTNonAlignedBoundingBox4180ToJSON
} from './';

/**
 * An axis-aligned bounding box indicated by two opposite corners.
 * @export
 * @interface BTBoundingBox1052
 */
export interface BTBoundingBox1052 {
    /**
     * Type of JSON object.
     * @type {string}
     * @memberof BTBoundingBox1052
     */
    btType?: string;
    /**
     * 
     * @type {BTVector3d389}
     * @memberof BTBoundingBox1052
     */
    maxCorner?: BTVector3d389;
    /**
     * 
     * @type {BTVector3d389}
     * @memberof BTBoundingBox1052
     */
    minCorner?: BTVector3d389;
    /**
     * 
     * @type {boolean}
     * @memberof BTBoundingBox1052
     */
    valid?: boolean;
}

/**
 * Check if a given object implements the BTBoundingBox1052 interface.
 */
export function instanceOfBTBoundingBox1052(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTBoundingBox1052FromJSON(json: any): BTBoundingBox1052 {
    return BTBoundingBox1052FromJSONTyped(json, false);
}

export function BTBoundingBox1052FromJSONTyped(json: any, ignoreDiscriminator: boolean): BTBoundingBox1052 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['btType'] === 'BTNonAlignedBoundingBox-4180') {
            return BTNonAlignedBoundingBox4180FromJSONTyped(json, true);
        }
    }
    return {
        
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'maxCorner': !exists(json, 'maxCorner') ? undefined : BTVector3d389FromJSON(json['maxCorner']),
        'minCorner': !exists(json, 'minCorner') ? undefined : BTVector3d389FromJSON(json['minCorner']),
        'valid': !exists(json, 'valid') ? undefined : json['valid'],
    };
}

export function BTBoundingBox1052SuperToJSON(value?: BTBoundingBox1052 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'btType': value.btType,
        'maxCorner': BTVector3d389ToJSON(value.maxCorner),
        'minCorner': BTVector3d389ToJSON(value.minCorner),
        'valid': value.valid,
    };
}



export function BTBoundingBox1052ToJSON(value?: BTBoundingBox1052 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (value.btType === 'BTNonAlignedBoundingBox-4180') {
        return BTNonAlignedBoundingBox4180ToJSON(value);
    }
    return BTBoundingBox1052SuperToJSON(value);
}
