/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * The Onshape REST API consumed by all client. # Authorization The simplest way to authorize and enable the **Try it out** functionality is to sign in to Onshape and use the current session. The **Authorize** button enables other authorization techniques. To ensure the current session isn\'t used when trying other authentication techniques, make sure to remove the Onshape cookie as per the instructions for your particular browser. Alternatively, a private or incognito window may be used. Here\'s [how to remove a specific cookie on Chrome](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site). - **Current Session** authorization is enabled by default if the browser is already signed in to [Onshape](/). - **OAuth2** authorization uses an Onshape OAuth2 app created on the [Onshape Developer Portal](https://dev-portal.onshape.com/oauthApps). The redirect URL field should include `https://cad.onshape.com/glassworks/explorer/oauth2-redirect.html`. - **API Key** authorization using basic authentication is also available. The keys can be generated in the [Onshape Developer Portal](https://dev-portal.onshape.com/keys). In the authentication dialog, enter the access key in the `Username` field, and enter the secret key in the `Password` field. Basic authentication should only be used during the development process since sharing API Keys provides the same level of access as a username and password.
 *
 * The version of the OpenAPI document: 1.170.23367-59c3c9f9feef
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTCompanySummaryInfo } from './BTCompanySummaryInfo';
import {
    BTCompanySummaryInfoFromJSON,
    BTCompanySummaryInfoFromJSONTyped,
    BTCompanySummaryInfoToJSON,
} from './BTCompanySummaryInfo';
import type { BTUserBasicSummaryInfo } from './BTUserBasicSummaryInfo';
import {
    BTUserBasicSummaryInfoFromJSON,
    BTUserBasicSummaryInfoFromJSONTyped,
    BTUserBasicSummaryInfoToJSON,
} from './BTUserBasicSummaryInfo';

/**
 * 
 * @export
 * @interface BTCompanyUserInfo
 */
export interface BTCompanyUserInfo {
    /**
     * 
     * @type {boolean}
     * @memberof BTCompanyUserInfo
     */
    admin?: boolean;
    /**
     * 
     * @type {BTCompanySummaryInfo}
     * @memberof BTCompanyUserInfo
     */
    company?: BTCompanySummaryInfo;
    /**
     * 
     * @type {string}
     * @memberof BTCompanyUserInfo
     */
    documentationNameOverride?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BTCompanyUserInfo
     */
    guest?: boolean;
    /**
     * URI to fetch complete information of the resource.
     * @type {string}
     * @memberof BTCompanyUserInfo
     */
    href?: string;
    /**
     * Id of the resource.
     * @type {string}
     * @memberof BTCompanyUserInfo
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof BTCompanyUserInfo
     */
    lastLoginTime?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof BTCompanyUserInfo
     */
    light?: boolean;
    /**
     * Name of the resource.
     * @type {string}
     * @memberof BTCompanyUserInfo
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof BTCompanyUserInfo
     */
    state?: number;
    /**
     * 
     * @type {BTUserBasicSummaryInfo}
     * @memberof BTCompanyUserInfo
     */
    user?: BTUserBasicSummaryInfo;
    /**
     * URI to visualize the resource in a webclient if applicable.
     * @type {string}
     * @memberof BTCompanyUserInfo
     */
    viewRef?: string;
}

/**
 * Check if a given object implements the BTCompanyUserInfo interface.
 */
export function instanceOfBTCompanyUserInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTCompanyUserInfoFromJSON(json: any): BTCompanyUserInfo {
    return BTCompanyUserInfoFromJSONTyped(json, false);
}

export function BTCompanyUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BTCompanyUserInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'admin': !exists(json, 'admin') ? undefined : json['admin'],
        'company': !exists(json, 'company') ? undefined : BTCompanySummaryInfoFromJSON(json['company']),
        'documentationNameOverride': !exists(json, 'documentationNameOverride') ? undefined : json['documentationNameOverride'],
        'guest': !exists(json, 'guest') ? undefined : json['guest'],
        'href': !exists(json, 'href') ? undefined : json['href'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lastLoginTime': !exists(json, 'lastLoginTime') ? undefined : (new Date(json['lastLoginTime'])),
        'light': !exists(json, 'light') ? undefined : json['light'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'user': !exists(json, 'user') ? undefined : BTUserBasicSummaryInfoFromJSON(json['user']),
        'viewRef': !exists(json, 'viewRef') ? undefined : json['viewRef'],
    };
}

export function BTCompanyUserInfoToJSON(value?: BTCompanyUserInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'admin': value.admin,
        'company': BTCompanySummaryInfoToJSON(value.company),
        'documentationNameOverride': value.documentationNameOverride,
        'guest': value.guest,
        'href': value.href,
        'id': value.id,
        'lastLoginTime': value.lastLoginTime === undefined ? undefined : (value.lastLoginTime.toISOString()),
        'light': value.light,
        'name': value.name,
        'state': value.state,
        'user': BTUserBasicSummaryInfoToJSON(value.user),
        'viewRef': value.viewRef,
    };
}

