/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://dev-portal.onshape.com/): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.176.31157-f17972084104
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BTCurveGeometryConic2284AllOf
 */
export interface BTCurveGeometryConic2284AllOf {
    /**
     * 
     * @type {string}
     * @memberof BTCurveGeometryConic2284AllOf
     */
    btType?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof BTCurveGeometryConic2284AllOf
     */
    points?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof BTCurveGeometryConic2284AllOf
     */
    rho?: number;
}

/**
 * Check if a given object implements the BTCurveGeometryConic2284AllOf interface.
 */
export function instanceOfBTCurveGeometryConic2284AllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTCurveGeometryConic2284AllOfFromJSON(json: any): BTCurveGeometryConic2284AllOf {
    return BTCurveGeometryConic2284AllOfFromJSONTyped(json, false);
}

export function BTCurveGeometryConic2284AllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): BTCurveGeometryConic2284AllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'points': !exists(json, 'points') ? undefined : json['points'],
        'rho': !exists(json, 'rho') ? undefined : json['rho'],
    };
}

export function BTCurveGeometryConic2284AllOfToJSON(value?: BTCurveGeometryConic2284AllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'btType': value.btType,
        'points': value.points,
        'rho': value.rho,
    };
}

