/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.196.54436-927372740f35
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BTMetadataPropertyUpdateParams
 */
export interface BTMetadataPropertyUpdateParams {
    /**
     * The id of the property that should be edited. This can be retrieved from MetadataCategory:getCategoryProperties.
     * @type {string}
     * @memberof BTMetadataPropertyUpdateParams
     */
    propertyId?: string;
    /**
     * The new value for the property.
     * @type {object}
     * @memberof BTMetadataPropertyUpdateParams
     */
    value?: object;
}

/**
 * Check if a given object implements the BTMetadataPropertyUpdateParams interface.
 */
export function instanceOfBTMetadataPropertyUpdateParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTMetadataPropertyUpdateParamsFromJSON(json: any): BTMetadataPropertyUpdateParams {
    return BTMetadataPropertyUpdateParamsFromJSONTyped(json, false);
}

export function BTMetadataPropertyUpdateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BTMetadataPropertyUpdateParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'propertyId': !exists(json, 'propertyId') ? undefined : json['propertyId'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function BTMetadataPropertyUpdateParamsToJSON(value?: BTMetadataPropertyUpdateParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'propertyId': value.propertyId,
        'value': value.value,
    };
}

