/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.196.54436-927372740f35
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTMReadOnlyParameter3800 } from './BTMReadOnlyParameter3800';
import {
    BTMReadOnlyParameter3800FromJSON,
    BTMReadOnlyParameter3800FromJSONTyped,
    BTMReadOnlyParameter3800ToJSON,
 BTMReadOnlyParameter3800SuperToJSON,
} from './BTMReadOnlyParameter3800';
import type { GBTNoticeLevel } from './GBTNoticeLevel';
import {
    GBTNoticeLevelFromJSON,
    GBTNoticeLevelFromJSONTyped,
    GBTNoticeLevelToJSON,
} from './GBTNoticeLevel';

/**
 * 
 * @export
 * @interface BTMParameterNotice4455
 */
export interface BTMParameterNotice4455 extends BTMReadOnlyParameter3800 {
    /**
     * Type of JSON object.
     * @type {string}
     * @memberof BTMParameterNotice4455
     */
    btType?: string;
    /**
     * 
     * @type {GBTNoticeLevel}
     * @memberof BTMParameterNotice4455
     */
    level?: GBTNoticeLevel;
    /**
     * 
     * @type {string}
     * @memberof BTMParameterNotice4455
     */
    message?: string;
}

/**
 * Check if a given object implements the BTMParameterNotice4455 interface.
 */
export function instanceOfBTMParameterNotice4455(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTMParameterNotice4455FromJSON(json: any): BTMParameterNotice4455 {
    return BTMParameterNotice4455FromJSONTyped(json, false);
}

export function BTMParameterNotice4455FromJSONTyped(json: any, ignoreDiscriminator: boolean): BTMParameterNotice4455 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...BTMReadOnlyParameter3800FromJSONTyped(json, ignoreDiscriminator),
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'level': !exists(json, 'level') ? undefined : GBTNoticeLevelFromJSON(json['level']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function BTMParameterNotice4455ToJSON(value?: BTMParameterNotice4455 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...BTMReadOnlyParameter3800SuperToJSON(value),
        'btType': value.btType,
        'level': GBTNoticeLevelToJSON(value.level),
        'message': value.message,
    };
}

