/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://dev-portal.onshape.com/): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.181.37085-cf05a13421a3
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTPExpression9 } from './BTPExpression9';
import {
    BTPExpression9FromJSON,
    BTPExpression9FromJSONTyped,
    BTPExpression9ToJSON,
 BTPExpression9SuperToJSON,
} from './BTPExpression9';
import type { BTPSpace10 } from './BTPSpace10';
import {
    BTPSpace10FromJSON,
    BTPSpace10FromJSONTyped,
    BTPSpace10ToJSON,
} from './BTPSpace10';
import type { GBTPDefinitionType } from './GBTPDefinitionType';
import {
    GBTPDefinitionTypeFromJSON,
    GBTPDefinitionTypeFromJSONTyped,
    GBTPDefinitionTypeToJSON,
} from './GBTPDefinitionType';

/**
 * 
 * @export
 * @interface BTPExpressionNew243
 */
export interface BTPExpressionNew243 extends BTPExpression9 {
    /**
     * Type of JSON object.
     * @type {string}
     * @memberof BTPExpressionNew243
     */
    btType?: string;
    /**
     * 
     * @type {BTPSpace10}
     * @memberof BTPExpressionNew243
     */
    spaceAfterBox?: BTPSpace10;
    /**
     * 
     * @type {BTPSpace10}
     * @memberof BTPExpressionNew243
     */
    spaceBetweenNewBox?: BTPSpace10;
    /**
     * 
     * @type {BTPExpression9}
     * @memberof BTPExpressionNew243
     */
    value?: BTPExpression9;
}

/**
 * Check if a given object implements the BTPExpressionNew243 interface.
 */
export function instanceOfBTPExpressionNew243(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTPExpressionNew243FromJSON(json: any): BTPExpressionNew243 {
    return BTPExpressionNew243FromJSONTyped(json, false);
}

export function BTPExpressionNew243FromJSONTyped(json: any, ignoreDiscriminator: boolean): BTPExpressionNew243 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...BTPExpression9FromJSONTyped(json, ignoreDiscriminator),
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'spaceAfterBox': !exists(json, 'spaceAfterBox') ? undefined : BTPSpace10FromJSON(json['spaceAfterBox']),
        'spaceBetweenNewBox': !exists(json, 'spaceBetweenNewBox') ? undefined : BTPSpace10FromJSON(json['spaceBetweenNewBox']),
        'value': !exists(json, 'value') ? undefined : BTPExpression9FromJSON(json['value']),
    };
}

export function BTPExpressionNew243ToJSON(value?: BTPExpressionNew243 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...BTPExpression9SuperToJSON(value),
        'btType': value.btType,
        'spaceAfterBox': BTPSpace10ToJSON(value.spaceAfterBox),
        'spaceBetweenNewBox': BTPSpace10ToJSON(value.spaceBetweenNewBox),
        'value': BTPExpression9ToJSON(value.value),
    };
}

