/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://dev-portal.onshape.com/): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.176.31157-f17972084104
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTPExpression9 } from './BTPExpression9';
import {
    BTPExpression9FromJSON,
    BTPExpression9FromJSONTyped,
    BTPExpression9ToJSON,
} from './BTPExpression9';
import type { BTPTypeName290 } from './BTPTypeName290';
import {
    BTPTypeName290FromJSON,
    BTPTypeName290FromJSONTyped,
    BTPTypeName290ToJSON,
} from './BTPTypeName290';

/**
 * 
 * @export
 * @interface BTPExpressionAs238AllOf
 */
export interface BTPExpressionAs238AllOf {
    /**
     * 
     * @type {string}
     * @memberof BTPExpressionAs238AllOf
     */
    btType?: string;
    /**
     * 
     * @type {BTPExpression9}
     * @memberof BTPExpressionAs238AllOf
     */
    operand?: BTPExpression9;
    /**
     * 
     * @type {BTPTypeName290}
     * @memberof BTPExpressionAs238AllOf
     */
    typeName?: BTPTypeName290;
}

/**
 * Check if a given object implements the BTPExpressionAs238AllOf interface.
 */
export function instanceOfBTPExpressionAs238AllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTPExpressionAs238AllOfFromJSON(json: any): BTPExpressionAs238AllOf {
    return BTPExpressionAs238AllOfFromJSONTyped(json, false);
}

export function BTPExpressionAs238AllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): BTPExpressionAs238AllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'operand': !exists(json, 'operand') ? undefined : BTPExpression9FromJSON(json['operand']),
        'typeName': !exists(json, 'typeName') ? undefined : BTPTypeName290FromJSON(json['typeName']),
    };
}

export function BTPExpressionAs238AllOfToJSON(value?: BTPExpressionAs238AllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'btType': value.btType,
        'operand': BTPExpression9ToJSON(value.operand),
        'typeName': BTPTypeName290ToJSON(value.typeName),
    };
}

