/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://dev-portal.onshape.com/): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.176.31157-f17972084104
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTPIdentifier8 } from './BTPIdentifier8';
import {
    BTPIdentifier8FromJSON,
    BTPIdentifier8FromJSONTyped,
    BTPIdentifier8ToJSON,
} from './BTPIdentifier8';
import type { BTPSpace10 } from './BTPSpace10';
import {
    BTPSpace10FromJSON,
    BTPSpace10FromJSONTyped,
    BTPSpace10ToJSON,
} from './BTPSpace10';
import type { BTPStatementBlock271 } from './BTPStatementBlock271';
import {
    BTPStatementBlock271FromJSON,
    BTPStatementBlock271FromJSONTyped,
    BTPStatementBlock271ToJSON,
} from './BTPStatementBlock271';
import type { GBTPType } from './GBTPType';
import {
    GBTPTypeFromJSON,
    GBTPTypeFromJSONTyped,
    GBTPTypeToJSON,
} from './GBTPType';

/**
 * 
 * @export
 * @interface BTPStatementTry1523AllOf
 */
export interface BTPStatementTry1523AllOf {
    /**
     * 
     * @type {BTPStatementBlock271}
     * @memberof BTPStatementTry1523AllOf
     */
    body?: BTPStatementBlock271;
    /**
     * 
     * @type {string}
     * @memberof BTPStatementTry1523AllOf
     */
    btType?: string;
    /**
     * 
     * @type {BTPStatementBlock271}
     * @memberof BTPStatementTry1523AllOf
     */
    catchBlock?: BTPStatementBlock271;
    /**
     * 
     * @type {BTPIdentifier8}
     * @memberof BTPStatementTry1523AllOf
     */
    catchVariable?: BTPIdentifier8;
    /**
     * 
     * @type {BTPIdentifier8}
     * @memberof BTPStatementTry1523AllOf
     */
    identifier?: BTPIdentifier8;
    /**
     * 
     * @type {boolean}
     * @memberof BTPStatementTry1523AllOf
     */
    silent?: boolean;
    /**
     * 
     * @type {BTPSpace10}
     * @memberof BTPStatementTry1523AllOf
     */
    spaceAfterCatch?: BTPSpace10;
    /**
     * 
     * @type {BTPSpace10}
     * @memberof BTPStatementTry1523AllOf
     */
    spaceBeforeSilent?: BTPSpace10;
    /**
     * 
     * @type {GBTPType}
     * @memberof BTPStatementTry1523AllOf
     */
    standardType?: GBTPType;
    /**
     * 
     * @type {string}
     * @memberof BTPStatementTry1523AllOf
     */
    typeName?: string;
}

/**
 * Check if a given object implements the BTPStatementTry1523AllOf interface.
 */
export function instanceOfBTPStatementTry1523AllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTPStatementTry1523AllOfFromJSON(json: any): BTPStatementTry1523AllOf {
    return BTPStatementTry1523AllOfFromJSONTyped(json, false);
}

export function BTPStatementTry1523AllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): BTPStatementTry1523AllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': !exists(json, 'body') ? undefined : BTPStatementBlock271FromJSON(json['body']),
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'catchBlock': !exists(json, 'catchBlock') ? undefined : BTPStatementBlock271FromJSON(json['catchBlock']),
        'catchVariable': !exists(json, 'catchVariable') ? undefined : BTPIdentifier8FromJSON(json['catchVariable']),
        'identifier': !exists(json, 'identifier') ? undefined : BTPIdentifier8FromJSON(json['identifier']),
        'silent': !exists(json, 'silent') ? undefined : json['silent'],
        'spaceAfterCatch': !exists(json, 'spaceAfterCatch') ? undefined : BTPSpace10FromJSON(json['spaceAfterCatch']),
        'spaceBeforeSilent': !exists(json, 'spaceBeforeSilent') ? undefined : BTPSpace10FromJSON(json['spaceBeforeSilent']),
        'standardType': !exists(json, 'standardType') ? undefined : GBTPTypeFromJSON(json['standardType']),
        'typeName': !exists(json, 'typeName') ? undefined : json['typeName'],
    };
}

export function BTPStatementTry1523AllOfToJSON(value?: BTPStatementTry1523AllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': BTPStatementBlock271ToJSON(value.body),
        'btType': value.btType,
        'catchBlock': BTPStatementBlock271ToJSON(value.catchBlock),
        'catchVariable': BTPIdentifier8ToJSON(value.catchVariable),
        'identifier': BTPIdentifier8ToJSON(value.identifier),
        'silent': value.silent,
        'spaceAfterCatch': BTPSpace10ToJSON(value.spaceAfterCatch),
        'spaceBeforeSilent': BTPSpace10ToJSON(value.spaceBeforeSilent),
        'standardType': GBTPTypeToJSON(value.standardType),
        'typeName': value.typeName,
    };
}

