/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * The Onshape REST API consumed by all client. # Authorization The simplest way to authorize and enable the **Try it out** functionality is to sign in to Onshape and use the current session. The **Authorize** button enables other authorization techniques. To ensure the current session isn\'t used when trying other authentication techniques, make sure to remove the Onshape cookie as per the instructions for your particular browser. Alternatively, a private or incognito window may be used. Here\'s [how to remove a specific cookie on Chrome](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site). - **Current Session** authorization is enabled by default if the browser is already signed in to [Onshape](/). - **OAuth2** authorization uses an Onshape OAuth2 app created on the [Onshape Developer Portal](https://dev-portal.onshape.com/oauthApps). The redirect URL field should include `https://cad.onshape.com/glassworks/explorer/oauth2-redirect.html`. - **API Key** authorization using basic authentication is also available. The keys can be generated in the [Onshape Developer Portal](https://dev-portal.onshape.com/keys). In the authentication dialog, enter the access key in the `Username` field, and enter the secret key in the `Password` field. Basic authentication should only be used during the development process since sharing API Keys provides the same level of access as a username and password.
 *
 * The version of the OpenAPI document: 1.171.24440-f37a82fd6450
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTTableAssemblyCrossHighlightDataItem2659 } from './BTTableAssemblyCrossHighlightDataItem2659';
import {
    BTTableAssemblyCrossHighlightDataItem2659FromJSON,
    BTTableAssemblyCrossHighlightDataItem2659FromJSONTyped,
    BTTableAssemblyCrossHighlightDataItem2659ToJSON,
} from './BTTableAssemblyCrossHighlightDataItem2659';
import type { BTTableBaseCrossHighlightData2609 } from './BTTableBaseCrossHighlightData2609';
import {
    BTTableBaseCrossHighlightData2609FromJSON,
    BTTableBaseCrossHighlightData2609FromJSONTyped,
    BTTableBaseCrossHighlightData2609ToJSON,
 BTTableBaseCrossHighlightData2609SuperToJSON,
} from './BTTableBaseCrossHighlightData2609';

/**
 * 
 * @export
 * @interface BTTableAssemblyCrossHighlightData2675
 */
export interface BTTableAssemblyCrossHighlightData2675 extends BTTableBaseCrossHighlightData2609 {
    /**
     * 
     * @type {string}
     * @memberof BTTableAssemblyCrossHighlightData2675
     */
    btType?: string;
    /**
     * 
     * @type {Array<BTTableAssemblyCrossHighlightDataItem2659>}
     * @memberof BTTableAssemblyCrossHighlightData2675
     */
    assemblyCrossHighlightItems?: Array<BTTableAssemblyCrossHighlightDataItem2659>;
}

/**
 * Check if a given object implements the BTTableAssemblyCrossHighlightData2675 interface.
 */
export function instanceOfBTTableAssemblyCrossHighlightData2675(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTTableAssemblyCrossHighlightData2675FromJSON(json: any): BTTableAssemblyCrossHighlightData2675 {
    return BTTableAssemblyCrossHighlightData2675FromJSONTyped(json, false);
}

export function BTTableAssemblyCrossHighlightData2675FromJSONTyped(json: any, ignoreDiscriminator: boolean): BTTableAssemblyCrossHighlightData2675 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...BTTableBaseCrossHighlightData2609FromJSONTyped(json, ignoreDiscriminator),
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'assemblyCrossHighlightItems': !exists(json, 'assemblyCrossHighlightItems') ? undefined : ((json['assemblyCrossHighlightItems'] as Array<any>).map(BTTableAssemblyCrossHighlightDataItem2659FromJSON)),
    };
}

export function BTTableAssemblyCrossHighlightData2675ToJSON(value?: BTTableAssemblyCrossHighlightData2675 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...BTTableBaseCrossHighlightData2609SuperToJSON(value),
        'btType': value.btType,
        'assemblyCrossHighlightItems': value.assemblyCrossHighlightItems === undefined ? undefined : ((value.assemblyCrossHighlightItems as Array<any>).map(BTTableAssemblyCrossHighlightDataItem2659ToJSON)),
    };
}

