/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.196.54436-927372740f35
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTOccurrence74 } from './BTOccurrence74';
import {
    BTOccurrence74FromJSON,
    BTOccurrence74FromJSONTyped,
    BTOccurrence74ToJSON,
} from './BTOccurrence74';
import type { GBTUiSelectionType } from './GBTUiSelectionType';
import {
    GBTUiSelectionTypeFromJSON,
    GBTUiSelectionTypeFromJSONTyped,
    GBTUiSelectionTypeToJSON,
} from './GBTUiSelectionType';

/**
 * 
 * @export
 * @interface BTUiSelection1185
 */
export interface BTUiSelection1185 {
    /**
     * Type of JSON object.
     * @type {string}
     * @memberof BTUiSelection1185
     */
    btType?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BTUiSelection1185
     */
    deterministicIdList?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BTUiSelection1185
     */
    id?: string;
    /**
     * 
     * @type {BTOccurrence74}
     * @memberof BTUiSelection1185
     */
    occurrence?: BTOccurrence74;
    /**
     * 
     * @type {string}
     * @memberof BTUiSelection1185
     */
    tableRowId?: string;
    /**
     * 
     * @type {GBTUiSelectionType}
     * @memberof BTUiSelection1185
     */
    type?: GBTUiSelectionType;
}

/**
 * Check if a given object implements the BTUiSelection1185 interface.
 */
export function instanceOfBTUiSelection1185(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTUiSelection1185FromJSON(json: any): BTUiSelection1185 {
    return BTUiSelection1185FromJSONTyped(json, false);
}

export function BTUiSelection1185FromJSONTyped(json: any, ignoreDiscriminator: boolean): BTUiSelection1185 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'deterministicIdList': !exists(json, 'deterministicIdList') ? undefined : json['deterministicIdList'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'occurrence': !exists(json, 'occurrence') ? undefined : BTOccurrence74FromJSON(json['occurrence']),
        'tableRowId': !exists(json, 'tableRowId') ? undefined : json['tableRowId'],
        'type': !exists(json, 'type') ? undefined : GBTUiSelectionTypeFromJSON(json['type']),
    };
}

export function BTUiSelection1185ToJSON(value?: BTUiSelection1185 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'btType': value.btType,
        'deterministicIdList': value.deterministicIdList,
        'id': value.id,
        'occurrence': BTOccurrence74ToJSON(value.occurrence),
        'tableRowId': value.tableRowId,
        'type': GBTUiSelectionTypeToJSON(value.type),
    };
}

