/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * The Onshape REST API consumed by all client. # Authorization The simplest way to authorize and enable the **Try it out** functionality is to sign in to Onshape and use the current session. The **Authorize** button enables other authorization techniques. To ensure the current session isn\'t used when trying other authentication techniques, make sure to remove the Onshape cookie as per the instructions for your particular browser. Alternatively, a private or incognito window may be used. Here\'s [how to remove a specific cookie on Chrome](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site). - **Current Session** authorization is enabled by default if the browser is already signed in to [Onshape](/). - **OAuth2** authorization uses an Onshape OAuth2 app created on the [Onshape Developer Portal](https://dev-portal.onshape.com/oauthApps). The redirect URL field should include `https://cad.onshape.com/glassworks/explorer/oauth2-redirect.html`. - **API Key** authorization using basic authentication is also available. The keys can be generated in the [Onshape Developer Portal](https://dev-portal.onshape.com/keys). In the authentication dialog, enter the access key in the `Username` field, and enter the secret key in the `Password` field. Basic authentication should only be used during the development process since sharing API Keys provides the same level of access as a username and password.
 *
 * The version of the OpenAPI document: 1.171.24804-920f3dc76f2b
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTCompanySummaryInfo } from './BTCompanySummaryInfo';
import {
    BTCompanySummaryInfoFromJSON,
    BTCompanySummaryInfoFromJSONTyped,
    BTCompanySummaryInfoToJSON,
} from './BTCompanySummaryInfo';
import type { BTUserSummaryInfo } from './BTUserSummaryInfo';
import {
    BTUserSummaryInfoFromJSON,
    BTUserSummaryInfoFromJSONTyped,
    BTUserSummaryInfoToJSON,
 BTUserSummaryInfoSuperToJSON,
} from './BTUserSummaryInfo';
import type { CompanyRole } from './CompanyRole';
import {
    CompanyRoleFromJSON,
    CompanyRoleFromJSONTyped,
    CompanyRoleToJSON,
} from './CompanyRole';
import type { GlobalPermissionInfo } from './GlobalPermissionInfo';
import {
    GlobalPermissionInfoFromJSON,
    GlobalPermissionInfoFromJSONTyped,
    GlobalPermissionInfoToJSON,
} from './GlobalPermissionInfo';

/**
 * 
 * @export
 * @interface BTUserAdminSummaryInfo
 */
export interface BTUserAdminSummaryInfo extends BTUserSummaryInfo {
    /**
     * 
     * @type {string}
     * @memberof BTUserAdminSummaryInfo
     */
    activePlanId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BTUserAdminSummaryInfo
     */
    billingUpdateRequired?: boolean;
    /**
     * 
     * @type {Array<CompanyRole>}
     * @memberof BTUserAdminSummaryInfo
     */
    companyRoles?: Array<CompanyRole>;
    /**
     * 
     * @type {Date}
     * @memberof BTUserAdminSummaryInfo
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof BTUserAdminSummaryInfo
     */
    forumId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BTUserAdminSummaryInfo
     */
    systemUser?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BTUserAdminSummaryInfo
     */
    totpEnabled?: boolean;
}

/**
 * Check if a given object implements the BTUserAdminSummaryInfo interface.
 */
export function instanceOfBTUserAdminSummaryInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTUserAdminSummaryInfoFromJSON(json: any): BTUserAdminSummaryInfo {
    return BTUserAdminSummaryInfoFromJSONTyped(json, false);
}

export function BTUserAdminSummaryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BTUserAdminSummaryInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...BTUserSummaryInfoFromJSONTyped(json, ignoreDiscriminator),
        'activePlanId': !exists(json, 'activePlanId') ? undefined : json['activePlanId'],
        'billingUpdateRequired': !exists(json, 'billingUpdateRequired') ? undefined : json['billingUpdateRequired'],
        'companyRoles': !exists(json, 'companyRoles') ? undefined : ((json['companyRoles'] as Array<any>).map(CompanyRoleFromJSON)),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'forumId': !exists(json, 'forumId') ? undefined : json['forumId'],
        'systemUser': !exists(json, 'systemUser') ? undefined : json['systemUser'],
        'totpEnabled': !exists(json, 'totpEnabled') ? undefined : json['totpEnabled'],
    };
}

export function BTUserAdminSummaryInfoToJSON(value?: BTUserAdminSummaryInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...BTUserSummaryInfoSuperToJSON(value),
        'activePlanId': value.activePlanId,
        'billingUpdateRequired': value.billingUpdateRequired,
        'companyRoles': value.companyRoles === undefined ? undefined : ((value.companyRoles as Array<any>).map(CompanyRoleToJSON)),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'forumId': value.forumId,
        'systemUser': value.systemUser,
        'totpEnabled': value.totpEnabled,
    };
}

