/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://dev-portal.onshape.com/): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.175.28944-54786a5810c9
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BTThumbnailInfo } from './BTThumbnailInfo';
import {
    BTThumbnailInfoFromJSON,
    BTThumbnailInfoFromJSONTyped,
    BTThumbnailInfoToJSON,
} from './BTThumbnailInfo';
import type { BTUserBasicSummaryInfo } from './BTUserBasicSummaryInfo';
import {
    BTUserBasicSummaryInfoFromJSON,
    BTUserBasicSummaryInfoFromJSONTyped,
    BTUserBasicSummaryInfoToJSON,
} from './BTUserBasicSummaryInfo';
import type { BTVersionInfo } from './BTVersionInfo';
import {
    BTVersionInfoFromJSON,
    BTVersionInfoFromJSONTyped,
    BTVersionInfoToJSON,
} from './BTVersionInfo';
import type { BTWorkspaceProtectionRuleOptions } from './BTWorkspaceProtectionRuleOptions';
import {
    BTWorkspaceProtectionRuleOptionsFromJSON,
    BTWorkspaceProtectionRuleOptionsFromJSONTyped,
    BTWorkspaceProtectionRuleOptionsToJSON,
} from './BTWorkspaceProtectionRuleOptions';

/**
 * 
 * @export
 * @interface BTWorkspaceInfo
 */
export interface BTWorkspaceInfo {
    /**
     * 
     * @type {boolean}
     * @memberof BTWorkspaceInfo
     */
    canDelete?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof BTWorkspaceInfo
     */
    createdAt?: Date;
    /**
     * 
     * @type {BTUserBasicSummaryInfo}
     * @memberof BTWorkspaceInfo
     */
    creator?: BTUserBasicSummaryInfo;
    /**
     * 
     * @type {string}
     * @memberof BTWorkspaceInfo
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof BTWorkspaceInfo
     */
    documentId?: string;
    /**
     * URI to fetch complete information of the resource.
     * @type {string}
     * @memberof BTWorkspaceInfo
     */
    href?: string;
    /**
     * Id of the resource.
     * @type {string}
     * @memberof BTWorkspaceInfo
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BTWorkspaceInfo
     */
    isReadOnly?: boolean;
    /**
     * 
     * @type {BTUserBasicSummaryInfo}
     * @memberof BTWorkspaceInfo
     */
    lastModifier?: BTUserBasicSummaryInfo;
    /**
     * 
     * @type {string}
     * @memberof BTWorkspaceInfo
     */
    microversion?: string;
    /**
     * 
     * @type {Date}
     * @memberof BTWorkspaceInfo
     */
    modifiedAt?: Date;
    /**
     * Name of the resource.
     * @type {string}
     * @memberof BTWorkspaceInfo
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof BTWorkspaceInfo
     */
    overrideDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof BTWorkspaceInfo
     */
    parent?: string;
    /**
     * 
     * @type {Array<BTVersionInfo>}
     * @memberof BTWorkspaceInfo
     */
    parents?: Array<BTVersionInfo>;
    /**
     * 
     * @type {BTWorkspaceProtectionRuleOptions}
     * @memberof BTWorkspaceInfo
     */
    protectionRule?: BTWorkspaceProtectionRuleOptions;
    /**
     * 
     * @type {BTThumbnailInfo}
     * @memberof BTWorkspaceInfo
     */
    thumbnail?: BTThumbnailInfo;
    /**
     * 
     * @type {string}
     * @memberof BTWorkspaceInfo
     */
    type?: string;
    /**
     * URI to visualize the resource in a webclient if applicable.
     * @type {string}
     * @memberof BTWorkspaceInfo
     */
    viewRef?: string;
}

/**
 * Check if a given object implements the BTWorkspaceInfo interface.
 */
export function instanceOfBTWorkspaceInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTWorkspaceInfoFromJSON(json: any): BTWorkspaceInfo {
    return BTWorkspaceInfoFromJSONTyped(json, false);
}

export function BTWorkspaceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BTWorkspaceInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'canDelete': !exists(json, 'canDelete') ? undefined : json['canDelete'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'creator': !exists(json, 'creator') ? undefined : BTUserBasicSummaryInfoFromJSON(json['creator']),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'documentId': !exists(json, 'documentId') ? undefined : json['documentId'],
        'href': !exists(json, 'href') ? undefined : json['href'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'isReadOnly': !exists(json, 'isReadOnly') ? undefined : json['isReadOnly'],
        'lastModifier': !exists(json, 'lastModifier') ? undefined : BTUserBasicSummaryInfoFromJSON(json['lastModifier']),
        'microversion': !exists(json, 'microversion') ? undefined : json['microversion'],
        'modifiedAt': !exists(json, 'modifiedAt') ? undefined : (new Date(json['modifiedAt'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'overrideDate': !exists(json, 'overrideDate') ? undefined : (new Date(json['overrideDate'])),
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
        'parents': !exists(json, 'parents') ? undefined : ((json['parents'] as Array<any>).map(BTVersionInfoFromJSON)),
        'protectionRule': !exists(json, 'protectionRule') ? undefined : BTWorkspaceProtectionRuleOptionsFromJSON(json['protectionRule']),
        'thumbnail': !exists(json, 'thumbnail') ? undefined : BTThumbnailInfoFromJSON(json['thumbnail']),
        'type': !exists(json, 'type') ? undefined : json['type'],
        'viewRef': !exists(json, 'viewRef') ? undefined : json['viewRef'],
    };
}

export function BTWorkspaceInfoToJSON(value?: BTWorkspaceInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'canDelete': value.canDelete,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'creator': BTUserBasicSummaryInfoToJSON(value.creator),
        'description': value.description,
        'documentId': value.documentId,
        'href': value.href,
        'id': value.id,
        'isReadOnly': value.isReadOnly,
        'lastModifier': BTUserBasicSummaryInfoToJSON(value.lastModifier),
        'microversion': value.microversion,
        'modifiedAt': value.modifiedAt === undefined ? undefined : (value.modifiedAt.toISOString()),
        'name': value.name,
        'overrideDate': value.overrideDate === undefined ? undefined : (value.overrideDate.toISOString()),
        'parent': value.parent,
        'parents': value.parents === undefined ? undefined : ((value.parents as Array<any>).map(BTVersionInfoToJSON)),
        'protectionRule': BTWorkspaceProtectionRuleOptionsToJSON(value.protectionRule),
        'thumbnail': BTThumbnailInfoToJSON(value.thumbnail),
        'type': value.type,
        'viewRef': value.viewRef,
    };
}

