/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.196.54436-927372740f35
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MaterialNormalTextureInfo } from './MaterialNormalTextureInfo';
import {
    MaterialNormalTextureInfoFromJSON,
    MaterialNormalTextureInfoFromJSONTyped,
    MaterialNormalTextureInfoToJSON,
} from './MaterialNormalTextureInfo';
import type { MaterialOcclusionTextureInfo } from './MaterialOcclusionTextureInfo';
import {
    MaterialOcclusionTextureInfoFromJSON,
    MaterialOcclusionTextureInfoFromJSONTyped,
    MaterialOcclusionTextureInfoToJSON,
} from './MaterialOcclusionTextureInfo';
import type { MaterialPbrMetallicRoughness } from './MaterialPbrMetallicRoughness';
import {
    MaterialPbrMetallicRoughnessFromJSON,
    MaterialPbrMetallicRoughnessFromJSONTyped,
    MaterialPbrMetallicRoughnessToJSON,
} from './MaterialPbrMetallicRoughness';
import type { TextureInfo } from './TextureInfo';
import {
    TextureInfoFromJSON,
    TextureInfoFromJSONTyped,
    TextureInfoToJSON,
} from './TextureInfo';

/**
 * 
 * @export
 * @interface Material
 */
export interface Material {
    /**
     * 
     * @type {number}
     * @memberof Material
     */
    alphaCutoff?: number;
    /**
     * 
     * @type {string}
     * @memberof Material
     */
    alphaMode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Material
     */
    doubleSided?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof Material
     */
    emissiveFactor?: Array<number>;
    /**
     * 
     * @type {TextureInfo}
     * @memberof Material
     */
    emissiveTexture?: TextureInfo;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof Material
     */
    extensions?: { [key: string]: object; };
    /**
     * 
     * @type {object}
     * @memberof Material
     */
    extras?: object;
    /**
     * 
     * @type {string}
     * @memberof Material
     */
    name?: string;
    /**
     * 
     * @type {MaterialNormalTextureInfo}
     * @memberof Material
     */
    normalTexture?: MaterialNormalTextureInfo;
    /**
     * 
     * @type {MaterialOcclusionTextureInfo}
     * @memberof Material
     */
    occlusionTexture?: MaterialOcclusionTextureInfo;
    /**
     * 
     * @type {MaterialPbrMetallicRoughness}
     * @memberof Material
     */
    pbrMetallicRoughness?: MaterialPbrMetallicRoughness;
}

/**
 * Check if a given object implements the Material interface.
 */
export function instanceOfMaterial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MaterialFromJSON(json: any): Material {
    return MaterialFromJSONTyped(json, false);
}

export function MaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): Material {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alphaCutoff': !exists(json, 'alphaCutoff') ? undefined : json['alphaCutoff'],
        'alphaMode': !exists(json, 'alphaMode') ? undefined : json['alphaMode'],
        'doubleSided': !exists(json, 'doubleSided') ? undefined : json['doubleSided'],
        'emissiveFactor': !exists(json, 'emissiveFactor') ? undefined : json['emissiveFactor'],
        'emissiveTexture': !exists(json, 'emissiveTexture') ? undefined : TextureInfoFromJSON(json['emissiveTexture']),
        'extensions': !exists(json, 'extensions') ? undefined : json['extensions'],
        'extras': !exists(json, 'extras') ? undefined : json['extras'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'normalTexture': !exists(json, 'normalTexture') ? undefined : MaterialNormalTextureInfoFromJSON(json['normalTexture']),
        'occlusionTexture': !exists(json, 'occlusionTexture') ? undefined : MaterialOcclusionTextureInfoFromJSON(json['occlusionTexture']),
        'pbrMetallicRoughness': !exists(json, 'pbrMetallicRoughness') ? undefined : MaterialPbrMetallicRoughnessFromJSON(json['pbrMetallicRoughness']),
    };
}

export function MaterialToJSON(value?: Material | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alphaCutoff': value.alphaCutoff,
        'alphaMode': value.alphaMode,
        'doubleSided': value.doubleSided,
        'emissiveFactor': value.emissiveFactor,
        'emissiveTexture': TextureInfoToJSON(value.emissiveTexture),
        'extensions': value.extensions,
        'extras': value.extras,
        'name': value.name,
        'normalTexture': MaterialNormalTextureInfoToJSON(value.normalTexture),
        'occlusionTexture': MaterialOcclusionTextureInfoToJSON(value.occlusionTexture),
        'pbrMetallicRoughness': MaterialPbrMetallicRoughnessToJSON(value.pbrMetallicRoughness),
    };
}

